### ISSUE TITLE
The problem in Firefox

### ISSUE THREAD

**Issue by Serg555** [JoomShaper/SP-Page-Builder#13]
Hi, I have an issue with Page builder. The problem happens only in Mozilla Firefox. There are no problems in the other browsers (Chrome, Safari, Opera, IE). The page is streched beyond the borders. Example of the such page: http://ngmsys.com/loyaltyprograms 
Thanks for your answer in advance.

**Comment by nayemmajhar** [comment]
Could you share a screenshot?

**Comment by Serg555** [comment]
There are two screenshots. One of them was made in Firefox, another one was made in Chrome.
![chrome](https://cloud.githubusercontent.com/assets/16303939/11813843/7f8ef02c-a354-11e5-9e18-4bd8f5cc9c20.jpg)

![firefox](https://cloud.githubusercontent.com/assets/16303939/11813839/755869bc-a354-11e5-81e9-8f65615af4a4.jpg)

**Comment by Serg555** [comment]
Yuo can see the problem in more detail on http://ngmsys.com/loyaltyprograms

**Comment by nayemmajhar** [comment]
This is not page builder issue.

```
#sp-page-builder .page-content .sppb-section {
    margin-top: 30px;
    z-index: 1;
    width: 75vw;
}
```

You have use `width:75vw` it's causes the issue.

**Comment by Serg555** [comment]
Nayem,
Actually your conclusion is absolutly  wrong. 

On the contrary, we've added "width:75vw" to temporary fix this issue. The problem return again if remove this line of code.

**Comment by nayemmajhar** [comment]
I changed the "width" using firebug and see the changes http://d.pr/i/v1cZ

**Comment by Serg555** [comment]
Neyem,

Please, see what's happened on my side when I've changed width value on "auto". So, the error repeated. It seems like the component doesn't understand the page width. As you can see on the screenshot the width is 3010px.

Thank you for support.

Serg
![error](https://cloud.githubusercontent.com/assets/16303939/12116276/aa344464-b3c9-11e5-82b5-5f24cb85bb4e.jpg)

**Comment by nayemmajhar** [comment]
Did you checked the red marked options to add a container in template?
![helix3 administration edit](https://cloud.githubusercontent.com/assets/3455568/12136437/e2342822-b471-11e5-9fe9-33669f501fbc.png)

**Comment by Serg555** [comment]
Nayem,

Thank you. I've found the problem.

This option is checked for all pages made by sp page builder. But if, at least, one column contain an image and option "fluid row" is checked then a page is reflected incorrect in Firefox.

Serg

**Comment by nayemmajhar** [comment]
Could you tell which one?

**Comment by Serg555** [comment]
The column with a smiling girl.
Thank you again. RIght now everything is work correctly.

Serg

**Comment by nayemmajhar** [comment]
You are welcome. Hope a great rating on JED. ;)
