### ISSUE TITLE
Redirection issue

### ISSUE THREAD

**Issue by daneshpayeh** [JoomShaper/SP-Page-Builder#15]
Hi guys,
Thank you for developing this powerful tools.
I have found a couple issues regarding redirection in page builder. And I believe it is page builder bugs.
The problem is that when I assign a page-builder page to home page, it doesn’t send the 404 error codes to “Redirect component” in Joomla!
This is my website and works fine:  https://ledsignsolution.com.au
But is you open a url that is not exist like  https://ledsignsolution.com.au/asdf
Instead of showing 404 error it will be redirected to home page with code 303 “see other”.

But It sometime works with some other url like:
https://ledsignsolution.com.au/led-signs-solutions/led-signs-for-restaurant-and-cafe
if instead of above url you type:
https://ledsignsolution.com.au/led-signs-solutions/led-signs-for-restaurant-and-cafeasdasd
It shows 404 error page and add a record in Redirect component.

Surprisingly if you try another one like:
https://ledsignsolution.com.au/electronic-signs/programmable-led-signs
and if instead of above url you type:
https://ledsignsolution.com.au/electronic-signs/programmable-led-signsasdasd
it redirect you to home page with 303 code!

But there is difference between these two links, in first url, no page is assigned to parent https://ledsignsolution.com.au/led-signs-solutions 
But is second one, a page is assigned to https://ledsignsolution.com.au/electronic-signs
Is that why first link shows 404 and the second redirect to homepage with 303!

I tried it with two webserver platform, Linux and Windows, both quick start pack and component only. The results is same. I active url rewriting and search engine friendly options in Joomla configuration. It is a big bug if you need to redesign a website and change the url structure. Because it affect you site SEO.
Please take a look at links and I hope you improve your already great page-builder.
Thanks,

**Comment by nayemmajhar** [comment]
Issue fixed https://github.com/JoomShaper/SP-Page-Builder/commit/98cf4993ef968b0d9f91305aac1feda4040c930e

**Comment by daneshpayeh** [comment]
Thank you. It works fine.

**Comment by nayemmajhar** [comment]
Don't forget to give a rating on JED.
