### ISSUE TITLE
Fatal error: Class 'JSNVersion' not found in /home/starsha3/public_html/texasscreens.com/administrator/components/com_pagebuilder/dependency.php on line 61

### ISSUE THREAD

**Issue by sunnystarshade** [JoomShaper/SP-Page-Builder#16]
I purchased pagebuilder but it won't install properly.
https://www.siteground.com/

Joomla backend
http://texasscreens.com/administrator/

Update: Don't give any site/user login credential publicly.

**Comment by nayemmajhar** [comment]
Please ask your question here https://www.joomshaper.com/forums by your puchased account user and password. JoomShaper support manager will help you. Thanks

**Comment by nayemmajhar** [comment]
This not SP Page Builder by JoomShaper. Please ask support to the actual author of your page builder. Thanks
