### ISSUE TITLE
SP Page Builder 

### ISSUE THREAD

**Issue by xyz231** [JoomShaper/SP-Page-Builder#19]
I have created several pages with the SP Page Builder. All can be opened for editing in the backend. Only one side can no longer be edited!? Here I get always shown a white page. In frontend all looks good.  What is the problem?

I include the following source code to show pictures:
`<div style="text-align: center;"><a class="jcepopup" href="http://IMAGE.jpg" target="_blank" data-mediabox-group="nature"> <img style="margin: 10px 5px 10px 0px; float: left;" src="/IMAGE.jpg" alt="" height="27" width="50"> </a> <a class="jcepopup" href="http://IMAGE.jpg" target="_blank" data-mediabox-group="nature"> <img style="margin: 10px 5px 10px 0px; float: left;" src="/IMAGE.jpg" alt="" height="27" width="50"> </a> <a class="jcepopup" href="http://IMAGE.jpg" target="_blank" data-mediabox-group="nature"> <img style="margin: 10px 5px 10px 0px; float: left;" src="/IMAGE.jpg" alt="" height="27" width="50"> </a></div>
<div style="clear: both; text-align: center;"><a class="jcepopup" href="http://IMAGE.jpg" target="_blank" data-mediabox-group="nature"> <img style="margin: 10px 5px 10px 0px; float: left;" src="/IMAGE.jpg" alt="" height="28" width="50"> </a> <a class="jcepopup" href="http://IMAGE.jpg" target="_blank" data-mediabox-group="nature"> <img style="margin: 10px 5px 10px 0px; float: left;" src="/IMAGE.jpg" alt="" height="28" width="50"> </a></div>`

On another page I had also incorporated source code, however, the presentation of the SP Page Builder changed, so I had to delete this page and create without the source code a new one.
The source code was for 7 red links. As seen in the screenshot:
![sp-page-builder-problem](https://cloud.githubusercontent.com/assets/16208615/13044421/5d26a32c-d3ce-11e5-856b-af85c08b92f6.png)

Excuse my bad English & thanks for help!

**Comment by nayemmajhar** [comment]
use "Text Block" add-on to show html source code to view. 

Here is video and doc too 

https://www.youtube.com/playlist?list=PL43bbfiC0wjhYCvEbl8B-fBVhHx4uh1zS

https://www.joomshaper.com/documentation/joomla-extensions/sp-page-builder

**Comment by xyz231** [comment]
Hi, Thanks for help!

 

I used "Text Block" add-on.

 

The page can not be opened for editing in Backend. Here I get always shown a white page. How can I get the contents turn again? 

 

Link (Frontend only for view) please do not publish: Gast // Gast

http://neu1.hauswelt-orth.de/index.php/aktuelles/projekte

 

Do you need access for backend?

 

_________________________________________

Von: Nayem Majhar [mailto:notifications@github.com] 
Gesendet: Donnerstag, 18. Februar 2016 07:01
An: JoomShaper/SP-Page-Builder <SP-Page-Builder@noreply.github.com>
Cc: xyz231 <katjawiemer@gmx.de>
Betreff: Re: [SP-Page-Builder] SP Page Builder (#19)

 

use "Text Block" add-on to show html source code to view. 

Here is video and doc too 

https://www.youtube.com/playlist?list=PL43bbfiC0wjhYCvEbl8B-fBVhHx4uh1zS

https://www.joomshaper.com/documentation/joomla-extensions/sp-page-builder

**Comment by xyz231** [comment]
The problem still exists.

**Comment by nayemmajhar** [comment]
Community discussion group https://www.facebook.com/groups/JoomlaPageBuilderCommunity/
