### ISSUE TITLE
Icon in Featured Box doesn't show

### ISSUE THREAD

**Issue by njj13** [JoomShaper/SP-Page-Builder#20]
Hi, 

I am having issue with the icon. I am using Feature Box function and the icon doesn't show on my web. Any idea why? Please advise.

http://imgur.com/fGInhGL

Thanks

**Comment by nayemmajhar** [comment]
here is the community discussion group https://www.facebook.com/groups/JoomlaPageBuilderCommunity/ People helps each others.
