### ISSUE TITLE
Validation errors (nested rows and empty target attribute)

### ISSUE THREAD

**Issue by xdcc** [JoomShaper/SP-Page-Builder#21]
Following code resembles a simple nested row: One row nested in another with no addons attached:

`<section  class="sppb-section " style="">
	<div class="sppb-row">
		<div class="sppb-col-sm-12">
			<div class="sppb-addon-container" style="" data-sppb-wow-duration="300ms">
				<section  class="sppb-section " style="">
					<div class="sppb-container-inner">
						<div class="sppb-row">
							<div class="sppb-col-sm-12">
								<div class="sppb-addon-container" style="">
								</div>
							</div>
						</div>
					</section>
				</div>
			</div>
		</div>
	</section>`

The div with class "sppb-addon-container" does not get closed -> validation error.

Fix: Close the mentioned div properly.

Links that don't have a specific target will have target="" which leads to a validation error.

Fix: Use target="_self" as default

Cheers,
Peter

**Comment by nayemmajhar** [comment]
If you are a premium user of Page Builder, ask the question in the forum. http://www.joomshaper.com/forums
