### ISSUE TITLE
some funny sql stuff, not cool!

### ISSUE THREAD

**Issue by Jirax** [JoomShaper/SP-Page-Builder#25]
Here is an error I am now getting with page builder since update:

Error

Unknown column 'a.catid' in 'on clause' SQL=SELECT COUNT(*) FROM #__sppagebuilder as a LEFT JOIN `#__languages` AS l ON l.lang_code = a.language LEFT JOIN #__users AS ua ON ua.id = a.created_user_id LEFT JOIN #__viewlevels AS ug ON ug.id = a.access LEFT JOIN #__categories AS c ON c.id = a.catid WHERE (a.published IN (0, 1))
Unknown column 'a.catid' in 'field list' SQL=SELECT a.id, a.title, a.alias, a.text, a.created_user_id,a.published, a.access, a.catid, a.ordering, a.created_time, a.created_user_id, a.language, a.hits,l.title AS language_title,ua.name AS author_name,ug.title AS access_title,c.title AS category_title FROM #__sppagebuilder as a LEFT JOIN `#__languages` AS l ON l.lang_code = a.language LEFT JOIN #__users AS ua ON ua.id = a.created_user_id LEFT JOIN #__viewlevels AS ug ON ug.id = a.access LEFT JOIN #__categories AS c ON c.id = a.catid WHERE (a.published IN (0, 1)) ORDER BY c.title asc, a.ordering asc LIMIT 0, 20
Unknown column 'a.catid' in 'on clause' SQL=SELECT COUNT(*) FROM #__sppagebuilder as a LEFT JOIN `#__languages` AS l ON l.lang_code = a.language LEFT JOIN #__users AS ua ON ua.id = a.created_user_id LEFT JOIN #__viewlevels AS ug ON ug.id = a.access LEFT JOIN #__categories AS c ON c.id = a.catid WHERE (a.published IN (0, 1)) = not to mention my site is now totally crashed.  :(

**Comment by nayemmajhar** [comment]
This problem occurs when you updating Page Builder version 1.6 or below to version 1.8 or later.
You must update Page Builder to 1.7 then update to latest version.

**Comment by Jirax** [comment]
ok, thanks for that... so do I downgrade then reupgrade?
On May 19, 2016 1:21 AM, "Nayem Majhar" <notifications@github.com> wrote:
>
> This problem occurs when you updating Page Builder version 1.6 or below
to version 1.8 or later.

**Comment by nayemmajhar** [comment]
Uninstall Page Builder then install version 1.0.7 then install version 1.0.8 or later. No worry to uninstall, Page Builder doesn't delete any data.

**Comment by nayemmajhar** [comment]
We recommended to backup before uninstall. Thanks

**Comment by Jirax** [comment]
naturally, once I uninstall, can I just install the newest release or go through his the release ladder?


Sent from my T-Mobile 4G LTE Device
-------- Original message --------From: Nayem Majhar <notifications@github.com> Date: 5/19/16  2:32 AM  (GMT-08:00) To: JoomShaper/SP-Page-Builder <SP-Page-Builder@noreply.github.com> Cc: Jirax <rbroganis@gmail.com>, Author <author@noreply.github.com> Subject: Re: [JoomShaper/SP-Page-Builder] some funny sql stuff, not cool!
  (#25) 
We recommended to backup before uninstall. Thanks

**Comment by Jirax** [comment]
ok, got it.... thank you


Sent from my T-Mobile 4G LTE Device
-------- Original message --------From: Nayem Majhar <notifications@github.com> Date: 5/19/16  2:24 AM  (GMT-08:00) To: JoomShaper/SP-Page-Builder <SP-Page-Builder@noreply.github.com> Cc: Jirax <rbroganis@gmail.com>, Author <author@noreply.github.com> Subject: Re: [JoomShaper/SP-Page-Builder] some funny sql stuff, not cool!
  (#25) 
Uninstall Page Builder then install version 1.0.7 then install version 1.0.8 or later. No worry to uninstall, Page Builder doesn't delete any data.

**Comment by nayemmajhar** [comment]
Just uninstall and then install latest version.
