### ISSUE TITLE
Calendar.setup: Nothing to setup (no fields found)

### ISSUE THREAD

**Issue by 313designs** [JoomShaper/SP-Page-Builder#27]
Greetings,

I'm on Joomla 3.5 and SP Page Builder 1.08.

All of a sudden I'm getting this error message when I open a page to  edit under SP Page Builder:

Calendar.setup:
Nothing to setup (no fields found). Please check your code "
Because of this error message, I cannot save my edits. The Save / Save & Close" buttons don't work under this component.

After researching several sites thus far, one of the issues can be the template.

I uninstalled my template and SP page Builder works fine. so its a conflict there.

Please help. This is a clients site and I need to make updates to it.

Thanks,
James

**Comment by nayemmajhar** [comment]
Send email at support@joomshaper.com and should write in the message that I ( Nayem Majhar ) am referring you.
