### ISSUE TITLE
Pagebreak / Loadmore Option

### ISSUE THREAD

**Issue by syhussaini** [JoomShaper/SP-Page-Builder#28]
Hello Team,

While working on a very long page with a list of different rows, I was falling lack of pagebreaks in the Page Buider. 
Is there a way we can have Pagebreaks in the SP Page Builder so that we can have the user click

<<Prev 1 2 3 4 Next>> something similar to Joomla.

We may also consider an alternate to this one i.e. add something that would inform user that there is more information ex: "Load More" at the desired rows of the page that is displayed at the end of the page so that user can click to expand the hidden parts of the page. If the page is too long, we can have multiple "Load More" added in different rows. This way the load time will also be controlled while trying to present a very long page.

I hope this will be considered as I am confident that this will be a great value addition.

Regards,
Syed H

**Comment by nayemmajhar** [comment]
So, It is not possible to a page break but we will add a feature to make the long page view in short.
