### ISSUE TITLE
YouTube Video Zoom Box Doesn't Work

### ISSUE THREAD

**Issue by uburoibob1** [JoomShaper/SP-Page-Builder#30]
Hi,

The YouTube video zoom box does not work on YouTube videos using the VIDEO add on Page Builder.

Here is our URL. Any of the videos on the home page illustrate the problem. Please let me know how to correct this.

http://wheatstone.com

Thanks,

Bob Martin

**Comment by nayemmajhar** [comment]
https://github.com/JoomShaper/SP-Page-Builder/commit/96d9623716f902d7981334d90b4477bbf74b32e6 video fullscreen/zoom issue fixed.

**Comment by uburoibob1** [comment]
Sorry, but it isn't working for us. I commented where you posted the fix, but here it is pasted for your convenience:

Thanks, for this, but it doesn't seem to work. The addon-parser.php causes my entire Pagebuilder layout to become unformatted. And the only difference I see between the two lines of code in that is an odd space after sppb-addon-container.

I have the css and js in place, but it makes no difference.

Here is the URL if you'd care to take a look: http://wheatstone.com

**Comment by nayemmajhar** [comment]
I think you edited video addons please see this file
https://github.com/JoomShaper/SP-Page-Builder/blob/master/site/addons/video/site.php

**Comment by nayemmajhar** [comment]
Check line 66 in site.php

**Comment by nayemmajhar** [comment]
Download this https://github.com/JoomShaper/SP-Page-Builder/archive/master.zip and install.

**Comment by uburoibob1** [comment]
OK! While I didn't reinstall SP Page Builder, your addons/video/site.php fix worked fine.

Thanks!

Bob

**Comment by uburoibob1** [comment]
I spoke too soon. Works in Firefox and Safari. In Chrome, it simply widens the entire window - not the YouTube video. Is there a line we can add to 66 to include Chrome?

**Comment by nayemmajhar** [comment]
Please contact to your theme provider. I think, they override the video add-on in the template. I do not see any change in HTML according to above fix.

**Comment by uburoibob1** [comment]
I have taken the above fix out because it was causing problems with Chrome browser. I can reinstate right now so you can take a look...

**Comment by uburoibob1** [comment]
OK, all that code is now in place.

**Comment by uburoibob1** [comment]
Here is a link to what happens in Chrome.

https://dl.dropboxusercontent.com/u/29489215/ExampleChrome.mov

**Comment by nayemmajhar** [comment]
Great. I see it's working.

**Comment by uburoibob1** [comment]
Yes, clearing the cache in Chrome made it work fine.

Thank you very much for staying with me on this one.

Bob

**Comment by uburoibob1** [comment]
So, quick question - will the next upgrade of SP Page Builder include these fixes? I ask as I am not the IT guy, just a designer and won't be the one upgrading the site. Do I need to keep these handy for if the functionality goes back to not working after any upgrade?

**Comment by nayemmajhar** [comment]
Yes. We release update version of SP Page Builder 1.1.0 and added this fix.

**Comment by uburoibob1** [comment]
Great. Again, thank you very much.
