### ISSUE TITLE
Pagebuilder Interface lost all formatting.

### ISSUE THREAD

**Issue by uburoibob1** [JoomShaper/SP-Page-Builder#32]
Yesterday I went to modify a page in SP Pagebuilder. When I opened it, this is what I saw. It's still like this. It's a very long page that's unformatted for Pagebuilder. Have you any suggestions about how to get the interface back? We can't really work in Pagebuilder until we solve this problem.

The rest of my site is fine, both admin and public.

Thanks,
Bob

![screen shot 2016-06-10 at 8 09 39 am](https://cloud.githubusercontent.com/assets/19615109/15963843/0b3161ae-2ee3-11e6-9aba-f54959c36252.png)

**Comment by nayemmajhar** [comment]
Send email at nayemmajhar@gmail.com

**Comment by uburoibob1** [comment]
I have emailed you.
