### ISSUE TITLE
No support for ShortCode

### ISSUE THREAD

**Issue by jfreak53** [JoomShaper/SP-Page-Builder#36]
I've tried in both the Pro and Free version and neither support using ShortCode tags in Text Block NOR HTML Block. This is extremely cumbersome because then we cannot specially format our text considering we are limited to using TinyMCE.

**Comment by nayemmajhar** [comment]
Why don't you use TinyMCE for HTML? Hope it will solve your problem.

**Comment by jfreak53** [comment]
That's what I'm using, PageBuilder only allows you to use TinyMCE, nothing else. Same outcome, whenever you put the character `]` in the editor window as text, be it TinyMCE or raw HTML, it doesn't matter it still breaks output.

**Comment by nayemmajhar** [comment]
Hope it will not happen in version 2.
