### ISSUE TITLE
Addons: 2 carousel cant work in same page

### ISSUE THREAD

**Issue by chidalgom1503** [JoomShaper/SP-Page-Builder#37]
hello,
having problems using 2 carousels in the same page, only the first works normal, but the second gets hide or moved out of the container, and dissapears from view, I noticed some change in html code of the carousel container div when a navigation arrow is clicked, this action removes all the classes preset and set some css code like position, margin, etc, and this is why the carousel is moved out from the container view.

Is there a solution for this?.
thanks

**Comment by nayemmajhar** [comment]
Add unique ID ( CSS id ) for  each carousel addon. It will fix this issue.
