### ISSUE TITLE
1064 error when opening index webpage

### ISSUE THREAD

**Issue by leslieongit** [JoomShaper/SP-Page-Builder#39]
# Steps to reproduce the issue

Edit a page via SP Page Builder > Duplicate the tabs into two >Work simultaneously > Visit site >Error

# Expected result

Load index page for website, as usual

# Actual result

1064 MySQL error

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AND (m.publish_up = '0000-00-00 00:00:00' OR m.publish_up <= '2016-09-21 09:30:1' at line 3 SQL=SELECT m.id, m.title, m.module, m.position, m.ordering, m.content, m.showtitle, m.params FROM #__modules AS m WHERE m.published = 1 AND m.id = AND (m.publish_up = '0000-00-00 00:00:00' OR m.publish_up <= '2016-09-21 09:30:18') AND (m.publish_down = '0000-00-00 00:00:00' OR m.publish_down >= '2016-09-21 09:30:18') AND m.access IN (1,1) AND m.client_id = 0

# System information (as much as possible)

Red Hat Enterprise Linux Platform
Dual Quad Core Intel® Xeon® processors
32 GB RAM
Dual SAS Drive (for the operating system)
RAID Mirroring (for the operating system)
Dual Power Supplies
Quad Gigabit Network Adapters

**Comment by nayemmajhar** [comment]
Did you create a long page? Is it open in front end? Let me know.

**Comment by leslieongit** [comment]
Yes i did so, its the Home Page. Its open right now

**Comment by leslieongit** [comment]
is it safe to post the website link still in development?

**Comment by nayemmajhar** [comment]
posting website link is safe but don't post credentials of the website in
publicly.

**Comment by leslieongit** [comment]
website link is www.demo.co.zw/nashpaints/
