### ISSUE TITLE
Flickr Gallery giving 404 server responded error

### ISSUE THREAD

**Issue by WGRAY01** [JoomShaper/SP-Page-Builder#41]
I'm getting a "Failed to load resource: the server responded with a status of 404 (Not Found)" error on my Helix 3 templated site with Page Builder Pro. I configured the Flickr Gallery with my Flicker ID and it show no images. This is for a flickr group. I used the link to find the id and placed it in there. Any idea as to why it doesn't pull in any images? I have my Flickr Group page settings set to Show group pool. This should show the group pool of the latest images posted to non-members. What can be going wrong here?

**Comment by nayemmajhar** [comment]
As a Page Builder Pro User, ask your question in JoomShaper Forum. Staffs will help you there.
